@startuml

rectangle "Copy results from scratch to home" {
caption \lpdsh -R ssh -w $SLURM_JOB_NODELIST "cp -r /mnt/local/scratch/$USER/results /home/$USER/results_\`hostname\`"
rectangle "<b>cpusm01\nExecutes the pdsh command" as job_executor
note left
  This is where slurm executes
  your submission script
end note
rectangle "<b>Lustre 5PB Storage" as Shared

rectangle "<b>cpusm01\nExecutes cp command" as Node1 {
  folder "/home/$USER" as Node1Home
  folder "/mnt/local/scratch/$USER" as Node1Scratch
}

rectangle "<b>cpusm02\nExecutes cp command" as Node2 {
  folder "/home/$USER" as Node2Home
  folder "/mnt/local/scratch/$USER" as Node2Scratch
}
rectangle "<b>cpusm03\nExecutes cp command" as Node3 {
  folder "/home/$USER" as Node3Home
  folder "/mnt/local/scratch/$USER" as Node3Scratch
}

job_executor -down-> Node1 : ssh
job_executor -down-> Node2 : ssh
job_executor -down-> Node3 : ssh

Node1Home <-up- Node1Scratch : \lcopy "results" folder\nas "results_cpusm01"\nto
Node2Home <-up- Node2Scratch : \lcopy "results" folder\nas "results_cpusm02"\nto
Node3Home <-up- Node3Scratch : \lcopy "results" folder\nas "results_cpusm03"\nto

Node1Home -[dashed]down-> Shared
Node2Home -[dashed]down-> Shared
Node3Home -[dashed]down-> Shared
}
@enduml
